# creation of ec2-instances and route 53 
- name: creation of ec2-instances
  hosts: all #local if we have inventory file
  connection: local
  vars:
    sg_id: "sg-08215fd9bc2dcf991"
    ami_id: "ami-0220d79f3f480ecf5"
    env: "dev"
    instances:
      - mongodb
      - catalogue
    domain_name: rubiya88s.online  
  tasks:
  ### creating ec2-instances #####
   - name: "creating ec2_instances"
     amazon.aws.ec2_instance:
       instance_type: "t3.micro"
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
       name: "{{ item }}-{{ env }}"

       tags:
         Project: roboshop
         Environment: "{{ env }}"
         component: "{{ item }}"
         Name: "{{ item }}-{{ env }}"
     loop: "{{ instances }}"
     register: ec2_output
      
   - name: "print ec2-instances output"
     ansible.builtin.debug:
       msg: "{{ ec2_output }}"
 ##### route 53 records ########
   - name: "craeting route53 records"
     amazon.aws.route53:
       state: present
       zone: "{{ domain_name }}"
       record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.rubiya88s.online, frontend-dev.rubiya88s.online
       type: A
       ttl: 1
       value: "{{ item.instances[0].private_ip_address }}"
      #  wait: true
     loop: "{{ ec2_output.results }}" # list

   - name: "craeting route53 record for frontend"
     amazon.aws.route53:
       state: present
       zone: "{{ domain_name }}"
       record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.rubiya88s.online, frontend-dev.rubiya88s.online
       type: A
       ttl: 1
       value: "{{ item.instances[0].public_ip_address }}"
      #  wait: true
     loop: "{{ ec2_output.results }}" # list 

